#
#
#
#   --------------------------------------------------------------
#   |                 ExtraordinaryGifts Plugin                  |
#   |   copyright (c) 2022 by Jan Komínek. All rights reserved.  |
#   |      More about a license on my github. Username: H7KZ     |
#   --------------------------------------------------------------
#
#
#

# ****----------------------------------------------****
# **                 GIFT PERMISSIONS                 **
# ****----------------------------------------------****
# CREATE GIFT PERMISSION
# [extraordinarygifts.gift.create]
# -----
# OPEN GIFT PERMISSION
# [extraordinarygifts.gift.open]
# -----
# SET GIFT TITLE PERMISSION
# [extraordinarygifts.gift.title]
# -----
# SET GIFT MESSAGE PERMISSION
# [extraordinarygifts.gift.message]
# -----
# RELOAD PLUGIN PERMISSION
# [extraordinarygifts.plugin.reload]
# -----
# COMMAND HELP PERMISSION
# [extraordinarygifts.command.help]
# -----
# COMMAND ECONOMY PERMISSION
# [extraordinarygifts.command.economy]
# -----
# COMMAND EGIFT PERMISSION
# [extraordinarygifts.command.egift]
# -----
# ALL COMMANDS BUT WITHOUT A RELOAD COMMAND PERMISSION
# [extraordinarygifts.command.allCommandsWithoutReload]
# -----
# ALL COMMANDS PERMISSION
# [extraordinarygifts.command.allCommandsWithReload]


# ****----------------------------------------------****
# **                  GIFT INVENTORY                  **
# ****----------------------------------------------****
"economy":
  # Enable economy
  "enabled": true
  # Gift economy
  "gift":
    # Enable gift economy
    "enabled": true
    # Allow shulker boxes as "money"
    "shulkerBox": true
    # List of items that can be used as "money"
    # Material + amount (max amount is 64 like a stack of blocks)
    "options":
      - "material": "DIAMOND"
        "amount": "10"
      - "material": "GOLD_INGOT"
        "amount": "25"
      - "material": "IRON_INGOT"
        "amount": "40"
    # Give "money" (Material + amount [the list ^]) back to the player when he opens the gift
    "giveBalanceBack": false
    # Give "money" (Shulker box) back to the player when he opens the gift
    "giveShulkerBoxBack": true



# ****----------------------------------------------****
# **                  GIFT INVENTORY                  **
# ****----------------------------------------------****
"giftInventory":
  "title": "§5§lGift Menu"
  # Size of the inventory (number of slots from 1 to 27)
  # If you set the size to lesser than 1 or greater than 27, the size will be set to default size of 27.
  "size": 27
  # Materials that are NOT allowed to be put into the inventory
  # Those Materials also include the gift item itself because of possible infinity inventory
  "banShulkerBoxes": true
  "bannedMaterials":
    - "BEDROCK"
    - "BARRIER"
  # GUI Items
  # For no title use " " with a space NOT "" without a space
  # You can set following properties:
  # Material, text and enchantment
  "gui":
    "acceptButton":
      "material": "GREEN_STAINED_GLASS_PANE"
      "text": "§a§lSelect appearance"
      "enchanted": true
    "cancelButton":
      "material": "RED_STAINED_GLASS_PANE"
      "text": "§c§lCancel"
      "enchanted": true
    "neutral":
      "material": "GRAY_STAINED_GLASS_PANE"
      "text": " "
      "enchanted": false


# ****----------------------------------------------****
# **                 GIFT APPEARANCE                  **
# ****----------------------------------------------****
"giftAppearance":
  # Name of the gift you will receive on creation
  "title": "§5§lSelect a gift appearance"
  # UUID of textures for the gifts
  # Array of UUIDs of textures for the gifts. Maximal number of textures/UUID is 45
  # When you have more than 45 textures, there won't be more than 45 textures in the gift
  # If array is empty, there will be set a default texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTcyNmQ5ZDA2MzJlNDBiZGE1YmNmNjU4MzliYTJjYzk4YTg3YmQ2MTljNTNhZGYwMDMxMGQ2ZmM3MWYwNDJiNSJ9fX0" (red gift)
  # To add a texture go to https://minecraft-heads.com/ and search for the head texture you want. Then copy the UUID of the texture to this array list.
  "items":
    - "name": "§3§lCyan gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGY1ODk4YWQ1NGU2MzRjNTlmYWI1YjI4NGQ0OWIzZTI1ZDAxNTUxMmNhYTNhYjU2MjBjZWNmMDBiODRmMTM0NSJ9fX0="
    - "name": "§9§lBlue gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTEyZTk0NTFjZGIxOTZiNzgxOTVhOGYwYTRiOWMxYzBhMDRmNTgyNzg4NzkyN2I2YTgyYWFkMzljYWIyZjQzMCJ9fX0="
    - "name": "§6§lGold gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI0Y2RlMTZhNDAxNGRlMGE3NjUxZjYwNjdmMTI2OTViYjVmZWQ2ZmVhZWMxZTk0MTNjYTQyNzFlN2M4MTkifX19"
    - "name": "§2§lGreen gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Y0MDc2NWE3NTBmMzhmMjI0YmI4ZGVmYWVlODA2YmI2MDU4Zjg0ODE4MzM4MTQ2ZWJmOTRhMDJlNjNkODg1ZiJ9fX0="
    - "name": "§c§lRed gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTcyNmQ5ZDA2MzJlNDBiZGE1YmNmNjU4MzliYTJjYzk4YTg3YmQ2MTljNTNhZGYwMDMxMGQ2ZmM3MWYwNDJiNSJ9fX0="
    - "name": "§e§lYellow gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTM3NTA2MWQwOGYxZDdiMzE3Njc1YWE3ZmE4ODAwZDZmMjA2NmUwMThkOWY5MWVjZGRmOWNhZjMwNGU5N2U5MiJ9fX0="
    - "name": "§a§lGreen gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODFlNDJlMzcyNWMyYjRhZTY5MDA1ODBjNGUyYTZiODMwZjZlY2EwMjExZjdhMzY0MTQzM2ZjNjdmYmM0M2QzZiJ9fX0="
    - "name": "§b§lAqua gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDZlMTJmZGFlMWZjZWJhNjg3OWY2NTk3OTYxMzJhN2ZmYTA4Y2Q5MmEyNmNiN2ExMDY3ZDQ5NzAzZDdiMWI0YiJ9fX0="
    - "name": "§d§lLilac gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGQyOWIwNmM3YzM3Y2JkMmE3NjU5MDgyNzdmYThlYWQwZTRkYzY2YTExM2YzNDdkZTNiYWI5MWZhZGU0NjkxMiJ9fX0="
    - "name": "§5§lPurple gift"
      "texture": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjBiNDVjYmZiZGZiNmRjNjY5NGRlOTZkOTdkYTM2YWU3YjVmZTNjZDk0YTViMjYyNTA1NTRjNWYwMjJjYTdkMCJ9fX0="
  # GUI Appearance Items
  # For no title use " " with a space NOT "" without a space
  # You can set following properties:
  # Material, text and enchantment
  "gui":
    "acceptButton":
      "material": "GREEN_STAINED_GLASS_PANE"
      "text": "§a§lCreate a gift"
      "enchanted": true
    "cancelButton":
      "material": "RED_STAINED_GLASS_PANE"
      "text": "§c§lCancel"
      "enchanted": true
    "neutral":
      "material": "GRAY_STAINED_GLASS_PANE"
      "text": " "
      "enchanted": false


# ****----------------------------------------------****
# **               GIFT TITLE SETTINGS                **
# ****----------------------------------------------****
# Default values for the gift title
"giftTitle":
  # Default color of the title
  "titleColor": "§d§l"
  # Maximum length of the title
  "maxTitleLength": 40
  # Maximum word length of the title
  "maxWordLength": 22
  # Forbidden words in the title
  "forbiddenWords":
    - "shit"
    - "fuck"
  # Forbidden characters in the title
  "forbiddenLetters":
    - '°'
    - '´'


# ****----------------------------------------------****
# **              GIFT MESSAGE SETTINGS               **
# ****----------------------------------------------****
# Default values for the gift message
"giftMessage":
  # Default color of the message
  "messageColor": "§7"
  # Maximum length of the message
  "maxMessageLength": 100
  # Maximum word length of the message
  "maxWordLength": 22
  # Maximum line length of the message
  "maxLineLength": 35
  # Forbidden words in the message
  "forbiddenWords":
    - "shit"
    - "fuck"
  # Forbidden characters in the message
  "forbiddenLetters":
    - '°'
    - '´'