#        ______     __                            ___                        _______ ______
#      / ____/  __/ /__________ _____  _________/ (_)___  ____ ________  __/ ____(_) __/ /______
#     / __/ | |/_/ __/ ___/ __ `/ __ \/ ___/ __  / / __ \/ __ `/ ___/ / / / / __/ / /_/ __/ ___/
#    / /____>  </ /_/ /  / /_/ / /_/ / /  / /_/ / / / / / /_/ / /  / /_/ / /_/ / / __/ /_(__  )
#   /_____/_/|_|\__/_/   \__,_/\____/_/   \__,_/_/_/ /_/\__,_/_/   \__, /\____/_/_/  \__/____/
#      ______            _____          _______ __     __         /____/
#     / ____/___  ____  / __(_)___ _   / ____(_) /__  / /
#    / /   / __ \/ __ \/ /_/ / __ `/  / /_  / / / _ \/ /
#   / /___/ /_/ / / / / __/ / /_/ /  / __/ / / /  __/_/
#   \____/\____/_/ /_/_/ /_/\__, /  /_/   /_/_/\___(_)
#                            /____/
#   --------------------------------------------------------------
#   |               ExtraordinaryGifts Config file               |
#   |   copyright (c) 2022 by Jan Komínek. All rights reserved.  |
#   --------------------------------------------------------------


# ****----------------------------------------------****
# **                   GIFT DATABASE                  **
# ****----------------------------------------------****

"database":

  # Path to the database file
  #        ˘folder˘        ˘file˘
  "path": "database/ExtraordinaryGifts.yml"

# ------------------------------------------------------



# ****----------------------------------------------****
# **              CUSTOM GIFT INVENTORY               **
# ****----------------------------------------------****

"giftInventory":

  # Size of the inventory (number of slots from 1 to 27)
  "size": 27

# ------------------------------------------------------
