name: ExtraordinaryGifts
version: '${version}'
main: cz.kominekjan.extraordinarygifts.ExtraordinaryGifts
api-version: 1.16
authors: [ Jan_Kominek ]
description: Plugin to send gifts
website: https://kominekjan.cz/
commands:
  egifts:
    usage: </command>
    description: Run ExtraordinaryGifts plugin
